apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

configMapGenerator:
  - name: autocare-api-config
    literals:
      - PORT=3000
      - NODE_ENV=production
      - FRONTEND_ORIGIN=/autocare
      - MAINTENANCE_SERVICE_URL=http://autocare-maintenance-service:8001
      - MAINTENANCE_SERVICE_TIMEOUT_MS=5000
      - DATABASE_PROVIDER=azure-sql
      - DATABASE_HOST=sql-azure-project.database.windows.net
      - DATABASE_PORT=1433
      - DATABASE_NAME=sqldb-autocare-prod
      - DATABASE_ENCRYPT=true
      - DATABASE_TRUST_SERVER_CERTIFICATE=false
      - DATABASE_USER=sqladmin

images:
  - name: acrazureproject.azurecr.io/autocare-api
    newName: acrazureproject.azurecr.io/autocare-api
    newTag: v1

patches:
  - target:
      kind: SecretProviderClass
      name: autocare-api-secrets
    patch: |-
      - op: replace
        path: /spec/secretObjects/0/data/0/objectName
        value: autocare-prod-sql-password
      - op: replace
        path: /spec/parameters/objects
        value: |
          array:
            - |
              objectName: autocare-prod-sql-password
              objectType: secret
