apiVersion: v1
kind: Service
metadata:
  name: autocare-api
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: autocare-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
