apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: autocare-api-secrets
  namespace: uat
spec:
  provider: azure
  secretObjects:
    - secretName: autocare-api-secrets
      type: Opaque
      data:
        - objectName: autocare-sql-password
          key: DATABASE_PASSWORD
  parameters:
    clientID: "037fe6d8-128e-4e44-bbda-2a910f758355"
    keyvaultName: "kv-azure-aks-project"
    tenantId: "a3c9a20a-5f7c-4023-a4a6-f0c1281063e2"
    objects: |
      array:
        - |
          objectName: autocare-sql-password
          objectType: secret
